### ISSUE TITLE
Details of the rendering shader

### ISSUE THREAD

**Issue by fire** [Gvgeo/Pivot-Painter-for-Blender#4]
I wish to make an engine enhancement compatible with Godot Game Engine, but there are several barriers.

This project is under a GPL license, and the UE4 project is proprietary. Godot Game Engine is under MIT license.

Can you do a write-up about what the programming is needed for the Godot Engine to implement an enhancement to read this plugin's output?

**Comment by Gvgeo** [comment]
I'm afraid, I won't be able to really help.
But at least did as very minimum, a list of the textures with their functions to look if need.

Couple things to keep in mind about the addon:
1. Code is a mess, and I don't plan to improve it. (It's my first bit of code, still has tons of notes to self. With only a couple small blender contributions improving my experience, don't expect much.)
2. Coordinates are taken from the world center, instead of the origin of active object or 3d cursor.
3. Some minor options have made to fit UE4, e.g. In "SelectionOrder" texture, order starts from 1 in UE4 instead of 0.

[TextureFuntions.txt](https://github.com/Gvgeo/Pivot-Painter-for-Blender/files/3850431/TextureFuntions.txt)

**Comment by fire** [comment]
I've modified your document and placed it https://github.com/fire/godot-pivot-painter/blob/master/reference-pivot-painter.md. Please review.

**Comment by Gvgeo** [comment]
Looks even better now.
I'll try to help if I can, in case you need anything more specific.

**Comment by fire** [comment]
Do you have a sample model? I prefer gltf2 as that's the working format for Godot 3.2.

**Comment by Gvgeo** [comment]
I have several samples preconfigured. 
Look at the **PivotPainter.blend** file **CubeTree** scene. Recreation of Ue4 example, is simple and easier to start and spot errors.
https://drive.google.com/drive/folders/1OQ_DwbMsR2QZnrKk-4144nJPH4av3LB-?usp=sharing

Just enable "Save Textures to folder" and Create Textures. Join the parts together afterwards, before export.

**Comment by fire** [comment]
I was distracted for a bit, will spend some time today.
